src/app/api/auth/[...nextauth]/route.ts

fixed oAth redirect url 
> https://github.com/BoostPerformance/fitculator-admin/issues/8
close #8

fix: fix oAuth error

---

src/app/api/auth/[...nextauth]/route.ts
src/app/auth/error/page.tsx
src/app/login/page.tsx
src/app/protected/page.tsx
src/components/accountInfo.tsx
src/components/buttons/googleButton.tsx
src/components/buttons/logoutButton.tsx
src/components/userPage/dashboardHeader.tsx
tsconfig.json

fixed google login error and added logout redirect page
> https://github.com/BoostPerformance/fitculator-admin/issues/11
close #11

fixed google login error and added logout redirect page

---

public/svg/arrow-down.svg
public/svg/arrow-right.svg
public/svg/arrow-up.svg
public/svg/calender.svg
src/app/api/auth/[...nextauth]/route.ts
src/app/login/page.tsx
src/app/user/diet/[id]/page.tsx
src/app/user/diet/page.tsx
src/components/accountInfo.tsx
src/components/dietDashboard/dietContainer.tsx
src/components/dietDashboard/dietTable.tsx
src/components/dietDashboard/totalFeedbackCount.tsx
src/components/input/dateInput.tsx
src/components/mock/DietItems.tsx

Applied Date data on the dashbaord list
> https://github.com/BoostPerformance/fitculator-admin/issues/18
close #18

Added features on diet dashboard

---

src/components/dietDashboard/dietContainer.tsx
src/components/dietDashboard/dietTable.tsx
src/components/dietItemContainer.tsx
src/components/input/dateInput.tsx
src/components/layout/mealPhotoLayout.tsx
src/components/mock/DietItems.tsx
src/components/textBox.tsx
src/types/mockType.ts

1. Restructured mock data by the supabase data table.
2. Changed data render structure on components.
3. Created additional comments modal on each meal.
4. Fixed feedback counts logic to calculated number.
> https://github.com/BoostPerformance/fitculator-admin/issues/20
close #20

Add features on Diet  and Diet detail page 

---

package-lock.json
package.json
public/svg/hamburger.svg
src/app/user/page.tsx
src/components/dietDashboard/dietTable.tsx
src/components/fixedBars/sidebar.tsx
src/components/graph/dailyDietRecord.tsx
src/components/graph/trafficSourceChart.tsx
src/components/graph/workoutLeaderboardItem.tsx
src/components/graph/workoutLeaderboeard.tsx
src/components/input/dateInput.tsx
src/components/input/searchInput.tsx
src/components/totalCounts/totalFeedbackCount.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/35
close #35

applied media queries in user page 

---

src/app/api/feedback-counts/route.ts
src/app/user/page.tsx
src/components/dietDashboard/dietTable.tsx
src/components/graph/dailyDietRecord.tsx
src/components/graph/trafficSourceChart.tsx
src/components/graph/workoutLeaderboeard.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/39
close #39

DailyDietREcord UI, data applying

---

src/app/api/challenges/route.ts
src/app/user/[challengeId]/diet/page.tsx
src/app/user/page.tsx
src/components/dietDashboard/dietDetailTable.tsx
src/components/input/dateInput.tsx
src/types/dietDetaileTableTypes.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/43
close #43

added Statics

---

src/app/user/[challengeId]/diet/page.tsx
src/app/user/page.tsx
src/components/dietDashboard/dietDetailTable.tsx
src/components/dietDashboard/dietTable.tsx
src/components/fixedBars/fixedBars.tsx
src/components/fixedBars/sidebar.tsx
src/components/input/dateInput.tsx
src/components/totalCounts/totalFeedbackCount.tsx
src/types/userPageTypes.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/45
close #45

made date picker & challenge period fetching

---

src/app/api/admin-users/route.ts
src/app/api/challenges/route.ts
src/app/user/[challengeId]/diet/page.tsx
src/components/dietDashboard/dietDetailTable.tsx
src/components/dietItemContainer.tsx
src/components/layout/mealPhotoLayout.tsx
src/components/utils/processMeals.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/55b
close #54

fetched QA mock data, total count statics par participants, and debugging

---

src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/app/user/[challengeId]/diet/[dailyRecordId]/page.tsx
src/app/user/[challengeId]/diet/page.tsx
src/app/user/[challengeId]/page.tsx
src/components/dietDashboard/dietContent.tsx
src/components/dietDashboard/dietDetailTable.tsx
src/components/dietItemContainer.tsx
src/components/dietItemContainerDebug.tsx
src/components/fixedBars/sidebar.tsx
src/components/input/dateInput.tsx
src/components/mobileChart.tsx
src/components/statistics/challengeStatistics.tsx
src/types/calendar.ts
src/types/dietDetaileTableTypes.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/56
close #56

flow through side bar

---

package-lock.json
package.json
prisma/schema.prisma
src/app/api/challenges/route.ts
src/app/api/coach-feedback/route.ts
src/app/api/coach-info/route.ts
src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/components/dietItemContainer.tsx
src/components/fixedBars/sidebar.tsx
src/components/hooks/useFeedback.ts
src/components/textBox.tsx
src/lib/prisma.ts
src/types/dietItemContainerTypes.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/60
close #60

coach memo POST, GET

---

src/app/api/challenge-participants/route.ts
src/app/user/[challengeId]/page.tsx
src/components/dietDashboard/dietTable.tsx
src/components/fixedBars/sidebar.tsx
src/components/graph/dailyDietRecord.tsx
src/components/graph/trafficSourceChart.tsx
src/components/layout/modal.tsx
src/components/statistics/challengeParticipantsDietStatics.tsx
src/types/userPageTypes.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/64
close #64

QA & coach memo modal

---

src/app/api/admin-users/route.ts
src/app/api/challenges/route.ts
src/app/api/coach-info/route.ts
src/app/api/workouts/route.ts
src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/app/user/[challengeId]/diet/page.tsx
src/app/user/[challengeId]/page.tsx
src/components/dietDashboard/dietContent.tsx
src/components/dietDashboard/dietDetailTable.tsx
src/components/graph/dailyDietRecord.tsx
src/components/mobileChart.tsx
src/components/statistics/dietStatistics.tsx
tailwind.config.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/66
close #66

media query

---

.gitignore
next.config.mjs
src/app/api/auth/[...nextauth]/route.ts
src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/72
close #72

cors error handling

---

src/components/mobileChart.tsx
src/types/dietDetaileTableTypes.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/74
close #74

QA button location added and changed

---

src/app/user/[challengeId]/page.tsx
src/components/dietDashboard/dietDetailTable.tsx

workout data는 아직 앱에서 받아오기 전이라 기다리는 중입니다. 
> https://github.com/BoostPerformance/fitculator-admin/issues/76
close #76

QA, korean time zone 

---

src/components/statistics/challengeParticipantsDietStatics.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/79
close #79

QA total count edited, feedback words count constrain removed

---

src/app/layout.tsx
src/app/user/[challengeId]/page.tsx
src/app/user/page.tsx
src/components/dietDashboard/dietTable.tsx
src/components/graph/dailyDietRecord.tsx
src/components/graph/trafficSourceChart.tsx
src/components/graph/workoutLeaderboeard.tsx
src/components/layout/title.tsx
src/components/totalCounts/totalFeedbackCount.tsx

> 유저페이지의 디자인 수정
> #81 
close #

[수정] 유저페이지 수정

---

src/app/layout.tsx
src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/app/user/[challengeId]/diet/page.tsx
src/app/user/[challengeId]/page.tsx
src/app/user/layout.tsx
src/app/user/page.tsx
src/components/dietItemContainer.tsx
src/components/graph/dailyDietRecord.tsx
src/components/graph/trafficSourceChart.tsx
src/components/graph/workoutLeaderboardItem.tsx
src/components/graph/workoutLeaderboeard.tsx
src/components/layout/title.tsx
src/components/totalCounts/totalFeedbackCount.tsx

1. favicon 연결
2. layout.tsx 생성
→ Sidebar컴포넌트와 main안의 children으로 구분
3. 전체적인 여백 수정
4. 통계카드 수정
→ 태블릿, 모바일 화면에서 white-space로 한줄로 보이도록 수정
5. 인기운동, 총 업로드 현황, 운동리더보드
→ 공통 : 데이터가 많아질 경우 볼 수 있도록 스크롤 추가
→ 인기운동의 경우 5% 이하의 운동종목은 그래프상 뜨지 않도록 설정
→ 총 업로드 현황의 경우 여백 조절 및 각 화면마다 폰트사이즈 수정
→ 운동리더보드의 경우 긴 이름은 짤리도록(스크롤 및 터치로 보도록)
→ prograss bar 길이고정
---
- PC 화면 <br /> 
<br />
- 태블릿 화면 <br />
<br />
- 모바일 화면<br />
> https://github.com/BoostPerformance/fitculator-admin/issues/91
close #

[생성/수정/스타일링] 유저 페이지

---

src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/components/dietDashboard/dietTable.tsx
src/components/layout/mealPhotoLayout.tsx
src/components/textBox.tsx

유저 페이지, 식단 페이지 스타일 수정
- 유저 페이지: 하단 피드백 컴포넌트 스타일 수정
- 식단 피드백  페이지: 전체 레이아웃 수정
> https://github.com/BoostPerformance/fitculator-admin/issues/
close #

[수정/스타일링] 유저 페이지, 식단 피드백 페이지/ 스타일 수정

---

src/components/fixedBars/sidebar.tsx

> 사이드바 마크업 수정, 챌린지 별 페이지 라우팅(임시)
> 아직 진행 중임
> https://github.com/BoostPerformance/fitculator-admin/issues/90

사이드바 수정 및 페이지 연결

---

src/app/api/auth/[...nextauth]/route.ts
src/app/api/challenge-participants/route.ts
src/app/api/challenges/route.ts
src/app/api/coach-feedback/route.ts
src/app/api/coach-info/route.ts
src/app/api/diet-table/route.ts
src/app/api/meals/route.ts
src/app/page.tsx
src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/components/dietDashboard/dietTable.tsx
src/components/fixedBars/sidebar.tsx
src/components/graph/dailyDietRecord.tsx
src/components/graph/workoutLeaderboard.tsx
src/components/hooks/useDietData.ts
src/components/hooks/useFeedback.ts

1. qa: enable date selection on calendar
2. deleted console
> https://github.com/BoostPerformance/fitculator-admin/issues/95
close #95

qa: enable date selection on calendar

---

src/app/api/meals/route.ts
src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/app/user/layout.tsx
src/components/layout/mealPhotoLayout.tsx
src/types/dietItemContainerTypes.ts

1. added meal data slideshow feature 
2. deleted console
> https://github.com/BoostPerformance/fitculator-admin/issues/97
close #97

qa: added meal data slideshow feature 

---

package-lock.json
package.json
src/app/api/workouts/route.ts
src/app/user/[challengeId]/page.tsx
src/components/graph/WeeklyWorkoutChart.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/99
close #99

weekly workout graph

---

src/components/graph/WeeklyWorkoutChart.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/101
close #101

added media query at weekly workout graph

---

src/components/graph/WeeklyWorkoutChart.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/103
close #103

edited data spreading methods

---

src/app/api/challenge-participants/route.ts
src/app/api/workouts/route.ts
src/components/dietDashboard/dietTable.tsx
src/types/userPageTypes.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/107
close #107

qa editing 

---

src/components/statistics/dietStatistics.tsx
src/components/workoutDashboard/workoutTable.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/112
close #112

fix: fix DietStatistics text

---

src/app/api/meals/route.ts
src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/components/input/dateInput.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/116
close #116

fix: fix total count card at diet page

---

src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/app/user/[challengeId]/workout/[userId]/page.tsx
src/app/user/[challengeId]/workout/page.tsx
src/components/statistics/excerciseStatistics.tsx
src/components/workoutDashboard/weeklyWorkoutChart.tsx
src/components/workoutDashboard/workoutTable.tsx

fix: fix diet total count days
> https://github.com/BoostPerformance/fitculator-admin/issues/119
close #119

design: apply media query at workout page / fix: diet statistics 

---

src/components/statistics/excerciseStatistics.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/121
close #121

fix: workout statistics media queries

---

src/app/api/user/route.ts
src/app/user/[challengeId]/workout/[userId]/page.tsx
src/app/user/[challengeId]/workout/page.tsx
src/components/hooks/useWorkoutData.ts
src/components/statistics/excerciseStatistics.tsx
src/components/totalCounts/totalFeedbackCount.tsx
src/components/workoutDashboard/workoutTable.tsx
src/types/workoutDetailPageType.ts
src/types/workoutTableTypes.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/126
close #126

fix: fix api connection and UI structure

---

src/app/api/admin-users/route.ts
src/app/api/workouts/weekly-categories/route.ts
src/app/user/[challengeId]/workout/[userId]/page.tsx
src/components/hooks/useWorkoutData.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/128
close #128

fix: graph display by weeks

---

src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/app/user/[challengeId]/workout/[userId]/page.tsx
src/components/fixedBars/sidebar.tsx
src/components/hooks/useWorkoutData.ts
src/components/textBox.tsx
src/components/workoutDashboard/workoutTable.tsx
src/types/useWorkoutDataTypes.ts
src/types/workoutTableTypes.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/130
close #130

fix: apply data on graphs

---

src/components/dietDashboard/dietDetailTable.tsx
src/components/fixedBars/sidebar.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/134
close #134

fix: fix to korean time zone at diet feedback updated_at

---

public/svg/plus.svg
src/app/user/[challengeId]/announcement/page.tsx
src/components/fixedBars/sidebar.tsx
src/components/input/noticeModal.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/137
close #137

design: announcement UI with mock data

---

public/svg/plus.svg
src/app/api/workouts/route.ts
src/app/user/[challengeId]/announcement/page.tsx
src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/app/user/[challengeId]/workout/[userId]/[week]/page.tsx
src/app/user/[challengeId]/workout/[userId]/page.tsx
src/components/fixedBars/sidebar.tsx
src/components/graph/generateCharts.tsx
src/components/hooks/useDietData.ts
src/components/hooks/useWorkoutData.ts
src/components/input/noticeModal.tsx
src/components/layout/customAlert.tsx
src/components/statistics/dietStatistics.tsx
src/components/workoutDashboard/weeklyWorkoutChart.tsx
src/components/workoutDashboard/workoutTable.tsx
src/components/workoutDashboard/workoutUserList.tsx
src/components/workoutpage/desktopWorkout.tsx
src/components/workoutpage/mobileWorkout.tsx
src/types/useWorkoutDataTypes.ts
src/types/workoutTableTypes.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/
close #

feat: create mobile workout page flow

---

src/app/api/challenges/route.ts
src/app/api/diet-table/route.ts
src/app/api/diet-upload-count/route.ts
src/app/user/[challengeId]/diet/page.tsx
src/components/hooks/useChallenges.ts
src/components/hooks/useDietData.ts
src/components/statistics/dietStatistics.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/142
close #142

fix: correct statistics at diet counts

---

src/app/api/diet-table/route.ts
src/app/api/meals/route.ts
src/app/user/[challengeId]/diet/[dailyRecordId]/[selectedDate]/page.tsx
src/components/dietDashboard/dietContent.tsx
src/components/dietDashboard/dietDetailTable.tsx
src/components/hooks/useDietData.ts
src/components/mobileChart.tsx
src/types/dietDetaileTableTypes.ts
src/types/dietItemContainerTypes.ts
src/types/mockType.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/144
close #144

feat: add water row at mobile and desktop table

---

src/components/fixedBars/sidebar.tsx
src/components/input/dateInput.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/146
close #146

fix: add date params for diet page

---

src/components/fixedBars/sidebar.tsx
src/components/statistics/dietStatistics.tsx
tailwind.config.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/147
close #147

css: fix sidebar media query and add  hover effect

---

src/app/user/[challengeId]/page.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/151
close #151

fix: dashboard

---

src/components/graph/trafficSourceChart.tsx
src/components/workoutDashboard/workoutUserList.tsx

> https://github.com/BoostPerformance/fitculator-admin/issues/160
close #160

fix: improved week count UI after 7th weeks

---

src/app/api/workouts/user-detail/route.ts
src/app/user/[challengeId]/workout/[userId]/[week]/page.tsx
src/app/user/[challengeId]/workout/[userId]/page.tsx
src/components/graph/generateCharts.tsx
src/components/hooks/useWorkoutData.ts
src/components/workoutDashboard/weeklyWorkoutChart.tsx
src/components/workoutpage/mobileWorkout.tsx
src/types/MobileWorkoutDetailType.ts

> https://github.com/BoostPerformance/fitculator-admin/issues/159
close #159

fix: fetch donut, bar graph
